[project]
name = "hilbert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ujjawalM", email = "ujjawal.m.wal@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ase>=3.29.0",
    "mace-torch>=0.3.16",
    "torch>=2.13.0",
    "jobserver",
]

[tool.uv.sources]
jobserver = { path = "../jobserver", editable = true }

[project.scripts]
hilbert = "hilbert:main"
hilbert-mlffopt = "hilbert.scripts.mlffopt_driver:main"
hilbert-xtbmd = "hilbert.scripts.xtbmd_driver:main"
hilbert-xtbopt = "hilbert.scripts.xtbopt_driver:main"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.4",
]

[tool.ruff]
line-length = 80
target-version = "py312"
src = ["src", "tests"]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort (import sorting)
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
]
ignore = []

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

